goal-app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, except: [:update, :edit, :destroy]

  resource :session, only: [:new, :create, :destroy]
end

goal-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

goal-app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true

  validates :password, length: { minimum: 6 }, allow_nil: true

  before_validation :ensure_session_token


  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user && user.is_password?(password)
      return user
    else
      return nil
    end
  end

  def is_password?(password)
    bcrypt_obj = BCrypt::Password.new(self.password_digest)
    bcrypt_obj.is_password?(password)
  end

  def generate_unique_session_token
    token = SecureRandom::urlsafe_base64
    while User.exists?(session_token: token)
      token = SecureRandom::urlsafe_base64
    end
    token
  end

  attr_reader :password

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def ensure_session_token
    self.session_token ||= generate_unique_session_token
  end

  def reset_session_token!
    self.session_token = generate_unique_session_token
    self.save!
    self.session_token
  end



end

goal-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def ensure_logged_in
    redirect_to new_session_url unless current_user
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token! if logged_in?
    session[:session_token] = nil
    @current_user = nil
  end

  def logged_in?
    !!current_user
  end

  def require_logged_out
    redirect_to users_url if logged_in?
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end


end

goal-app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ['Sike b*tch']
      render :new
    end
  end


  def destroy
    logout!
    redirect_to new_session_url
  end

end

goal-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
    render :index
  end

  def new
    render :new
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ["Username or password invalid"]
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

goal-app/app/helpers/application_helper.rb
module ApplicationHelper
end

goal-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>

    <h1>Goals</h1>

    <% if !logged_in? %>
      <a href="<%= new_user_url%>">Sign up</a>
      <a href="<%= new_session_url%>">Login</a>
    <% else %>


      <% if current_user.username == 'Kelly' %>
        <% 100.times do %>
          <h1>Kelly SUCKS</h1>
        <% end %>
      <% end %>
        <h3>Howdy there, <%= current_user.username %>!</h3>
      

      <form action="<%= session_url %>" method="POST">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="hidden" name="_method" value="delete">
      <input type="submit" value="Logout"> 
      </form>
    <% end %>
      
      

    <%= yield %>
  </body>
</html>

goal-app/app/views/users/index.html.erb
<h3>Users index!</h3>

<ul>
  <% @users.each do |user| %>
    <li><%= user.username %> is a G</li>
  <% end %>



</ul>

goal-app/app/views/users/new.html.erb
<h3>Sign up page</h3>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="username">Username: </label>
  <input type="text" id="username" name="user[username]">

  <br>

  <label for="password">Password: </label>
  <input type="password" id="password" name="user[password]">

  <br>

  <input type="submit" value="Sign up babycakes">




</form>

goal-app/app/views/users/show.html.erb
<h3>Show page</h3>

<p>What's poppin <%= @user.username %></p>